name: license-check
on: pull_request
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check License Header
      uses: apache/skywalking-eyes/header@6ac35584d6f923b6cb62f1ae8682c5bc60b537e4
