name: license-check
on: pull_request
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check License Header
      uses: apache/skywalking-eyes/header@c72515a64b6445f7b079c9cb517271ff65410948
